# Generated by Django 5.2.8 on 2026-01-27 19:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Публичный UUID для использования в API', null=True, unique=True)),
                ('name', models.CharField(help_text='Название репозитория', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False, help_text='Приватный репозиторий (только для владельца и коллабораторов)')),
                ('is_read_only', models.BooleanField(default=False, help_text='Режим только для чтения (для всех пользователей)')),
                ('owner_id', models.IntegerField(help_text='ID пользователя-владельца репозитория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['public_id'], name='repositorie_public__c4306f_idx'), models.Index(fields=['created_at'], name='repositorie_created_7547f9_idx'), models.Index(fields=['owner_id'], name='repositorie_owner_i_f7dc4a_idx'), models.Index(fields=['is_private'], name='repositorie_is_priv_58c2b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID пользователя-коллаборатора')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя (username) коллаборатора', max_length=150, null=True)),
                ('role', models.CharField(choices=[('read', 'Чтение'), ('write', 'Запись'), ('admin', 'Администратор')], default='write', help_text='Роль коллаборатора в репозитории', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='version_management.repository')),
            ],
            options={
                'verbose_name_plural': 'Collaborators',
                'db_table': 'collaborators',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['repository', 'user_id'], name='collaborato_reposit_06829d_idx'), models.Index(fields=['user_id'], name='collaborato_user_id_9417f9_idx'), models.Index(fields=['username'], name='collaborato_usernam_38eb0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'user_id'), name='unique_collaborator_per_repository')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя ветки (например: main, develop, feature/x)', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_default', models.BooleanField(default=False, help_text='Ветка по умолчанию для этого репозитория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='version_management.repository')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['repository', '-is_default', 'name'],
                'indexes': [models.Index(fields=['repository', 'created_at'], name='branches_reposit_f252cf_idx'), models.Index(fields=['repository', 'is_default'], name='branches_reposit_b8b092_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'name'), name='unique_branch_name_per_repository'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('repository',), name='only_one_default_branch_per_repository')],
            },
        ),
    ]
