# Generated by Django 5.2.8 on 2026-01-20 12:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Публичный UUID для использования в API', null=True, unique=True)),
                ('name', models.CharField(help_text='Название репозитория', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['public_id'], name='repositorie_public__c4306f_idx'), models.Index(fields=['created_at'], name='repositorie_created_7547f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя ветки (например: main, develop, feature/x)', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_default', models.BooleanField(default=False, help_text='Ветка по умолчанию для этого репозитория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='version_management.repository')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['repository', '-is_default', 'name'],
                'indexes': [models.Index(fields=['repository', 'created_at'], name='branches_reposit_f252cf_idx'), models.Index(fields=['repository', 'is_default'], name='branches_reposit_b8b092_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'name'), name='unique_branch_name_per_repository'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('repository',), name='only_one_default_branch_per_repository')],
            },
        ),
    ]
