# Generated by Django 5.2.8 on 2026-01-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
