# Generated by Django 5.2.8 on 2026-01-20 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Публичный UUID для использования в API', null=True),
        ),
    ]
