# Generated by Django 5.2.8 on 2026-01-10 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['repository', '-is_default', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name'], 'verbose_name_plural': 'Repositories'},
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_owner_i_edda75_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Имя ветки (например: main, develop, feature/x)', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(help_text='Название репозитория', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
